### ISSUE TITLE
Implement IsTestkit in Mira Configuration Block

### ISSUE THREAD

**Issue by kiwidoggie** [OpenOrbis/mira-project#113]
Testkits use different ShellCore offsets and what not, instead of creating a whole new platform that would be very annoying to keep maintained, add a flag in Mira's configuration block on first bootup determining if a unit is a testkit, or dev, or retail. Then from there apply required patches in each of the required locations that are testkit specific.

This will fix now closed PR: https://github.com/OpenOrbis/mira-project/pull/86

**Comment by LightningMods** [comment]
https://github.com/OpenOrbis/mira-project/pull/120

Added testkit checks feel free to edit
