### ISSUE TITLE
[REQ] 5.03 Firmware Support

### ISSUE THREAD

**Issue by kimou503** [OpenOrbis/mira-project#122]
I have a ps4 5.03 bd . I like to use mira . I was used a binloader(4.55-5.07). For upload miraloader and mira.bin . But not worked . Thak you for help me to use mira.

**Comment by sleirsgoevy** [comment]
AFAIK there are no payloads targeting 5.03, and 5.05 ones are not compatible. You will need to update to 5.05 somehow.

**Comment by kimou503** [comment]
I cant update my ps4 because my bleu ray is broken

**Comment by kiwidoggie** [comment]
Closing as duplicate of #139
