### ISSUE TITLE
Log server won't accept connections after client drops

### ISSUE THREAD

**Issue by Cryptogenic** [OpenOrbis/mira-project#18]
If a client drops the connection to the log server suddenly (for example, if a C# application connects to Mira but does not disconnect gracefully before the application closes), it effectively DoS's the server. It will not accept any new connections, and a console reboot + Mira reload is required to connect to the log server. This is an issue that will likely need to be addressed before release.

**Comment by kiwidoggie** [comment]
Closing as this is being moved to daemon and removed from the kernel
