### ISSUE TITLE
Need printf hook to print to klog

### ISSUE THREAD

**Issue by Cryptogenic** [OpenOrbis/mira-project#51]
Samples from the toolchain and what not that printf() cannot be captured by reading kernel log. Adding the hook for this into Mira would add convenience here.

**Comment by idc** [comment]
https://gist.github.com/idc/aada292e9e26b4fd7ce1947510a09571

Quick & dirty version. @Al-Azif provided some other version offsets in comment.

**Comment by 0x90h** [comment]
this does workfor me 5.05retail not sure about third one 
    // route deci_tty_write to ttyconsdev_write in deci_tty_cdev structure
    *(uint64_t*)&gKernelBase[0x19FC168] = (uint64_t)&gKernelBase[0x000ECAC0];
 
	kmem = (uint8_t *)&gKernelBase[0x00436136];
	kmem[0] = 0xEB;
	kmem[1] = 0x1E;
 
	kmem = (uint8_t *)&gKernelBase[0x00436136];
	kmem[0] = 0xEB;
	kmem[1] = 0x1E;
