### ISSUE TITLE
Known bugs when using mira

### ISSUE THREAD

**Issue by Leeful** [OpenOrbis/mira-project#53]
Here is a list of bugs I have found while using mira (5.05):

- PS2 games made with PS4 PS2 Classics GUI stay on loading screen and will not load.
- Remote Package Installer will not load (says corrupt).
- The Debug Settings option disappears after you have used rest mode.
- Games crash on resuming from rest mode if you enter rest mode with game running.

If I find any more bugs I'll update the list. 
Hope this is useful :)

**Comment by kiwidoggie** [comment]
@Leeful can you see if the PS2 classics gui games and the remote package installer loads with http://fuxur.faith/Mira_Orbis_MIRA_PLATFORM_ORBIS_BSD_505.elf

(OO homebrew won't load with this, but need to test something)

**Comment by Leeful** [comment]
@kiwidoggie No they do not load with that either.

The only difference is that with the original build, if I try and run Remote Package Installer I get 2 popups saying...

**_Sysmodule:
libSceFios2.sprx is loaded from the
development machine system._**

Then the PS4 says the application is corrupt and cannot load.
But when I try it with this build it just instantly says that the application is corrupt and cannot load with no popup.

There is no change with the PS2 classics gui games, they just stay on the loading image.

**Comment by Leeful** [comment]
UPDATE:
Using the latest [build](https://github.com/OpenOrbis/mira-project/actions/runs/108922374) from Specter, several of the issues I mentioned now work.

PS2 Classics GUI games now work.
Debug settings now remain after you resume from rest mode and rest mode itself now seems to work if you use it with a game running. (only tested this once!, there might still be issues)

Remote Package Installer still does not work though.
It now loads without an error but you are unable to send any pkg's to it.
Also, once when I tried to run it it just froze the console.

**Comment by krugdenis** [comment]
Does anyone have troubles with installing fpkgs on 6.72? Using external HDD it is getting slowdowns after some time, dropping speed from 100 mbps to 1-3 mbps. The same is using RPI - after sending >= 30 Gbs speed is dropping. Maybe internal HDD issue, but after reboot transfer speed is back to normal for some time.

**Comment by kiwidoggie** [comment]
Hey @Leeful I have created the issue #98 for tracking, do the PS2 Classics GUI games now work or should that be another issue created?

**Comment by Joonie86** [comment]
Tested Demento and SNES Station and all worked fine. Closing this.
