### ISSUE TITLE
Add Remote PKG Installer Support

### ISSUE THREAD

**Issue by kiwidoggie** [OpenOrbis/mira-project#98]
Currently there are some patches missing to allow Remote PKG Support

Linking to #84 and #98  as it seems to have a bunch of stuff required for this.

**Comment by Joonie86** [comment]
This currently works fine though? ready for closing? @Al-Azif @kiwidoggie

**Comment by Al-Azif** [comment]
I added the offsets to #108 after it's accepted it should just be adding the patch to the FakePKG plugin along with the other tweaks

**Comment by Al-Azif** [comment]
Added in Pull #118
